name: pocket_game_maker
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  flutter_inappwebview: 6.2.0-beta.3
  archive: ^3.6.1
  share_plus: ^10.0.2

flutter:
  uses-material-design: true
  assets:
    - engine/pocket_runtime.js